name: virtual_try_on
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  # flutter_unity_widget: ^2020.3.25

  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  http: ^1.2.0
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/shoe1.png
    - assets/shoe2.png
    - assets/shoe3.png

  fonts:
    - family: Inter
      fonts:
        - asset: assets/Inter-Regular.ttf
        - asset: assets/Inter-Medium.ttf
          weight: 500
        - asset: assets/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/Inter-Bold.ttf
          weight: 700
